apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: loginservice
  name: loginservice
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    app: loginservice
status:
  loadBalancer: {}
