version: "3.9"

services:

  jenkins:
    image: "jenkins/jenkins"
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
