version: "3.9"

services:

  jenkins:
    image: "jenkins/jenkins"
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

#  ngrok:
#    image: ngrok/ngrok
#    depends_on:
#      - jenkins
#    environment:
#      NGROK_AUTHTOKEN: 2JCa9YEAGAA4SxhEpnDFqOIHkOO_2PFgpicE6pVkvgQs7GqZD
#    command: http jenkins:8080

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    ports:
      - "5432:5432"
    networks:
      - tools
    volumes:
      - ./postgres/data:/var/lib/postgres/data


  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonarqube/sonarqube_data:/opt/sonarqube/data
      - ./sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube/sonarqube_logs:/opt/sonarqube/logs
      - ./sonarqube/sonarqube_temp:/opt/sonarqube/temp


volumes:
  jenkins_home:
