version: "3.9"

services:

  dataservice:
    image: "nickzay/dataservice"
    ports:
      - "7777:7777"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret

  loginservice:
    image: "nickzay/loginservice"
    ports:
      - "8888:8888"
    depends_on:
      - dataservice
    environment:
      DATA_SERVICE_URL: http://dataservice:7777/

  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
