apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dataservice
  name: dataservice
spec:
  ports:
    - name: "7777"
      port: 7777
      targetPort: 7777
  selector:
    app: dataservice
status:
  loadBalancer: {}
